using Core.DTOs;

namespace Core.Interfaces.Accessors
{
    /// <summary>
    /// Accessor for interacting with PaymentSpring APIs
    /// </summary>
    public interface IPaymentAccessor
    {
        /// <summary>
        /// Gets a user's payment info from PaymentSpring with their PaymentSpring Customer ID.
        /// </summary>
        /// <param name="customerID">The customer id provided by PaymentSpring associated with the customer</param>
        /// <returns>A user's payment info provided by PaymentSpring/returns>
        UserPaymentInfoDTO GetPaymentInfoForCustomer(string customerID);

        /// <summary>
        /// Charges a customer through PaymentSpring.
        /// </summary>
        /// <param name="payment">The payment DTO, containing necessary information to charge through PaymentSpring</param>
        /// <returns>The charge result from PaymentSpring</returns>
        ChargeResultDTO ChargeCustomer(PaymentDTO payment);

        /// <summary>
        /// Creates a new customer with paymentSpring
        /// </summary>
        /// <param name="customerInfo">The information neccessary</param>
        /// <returns>The customer id generated by paymentSpring</returns>
        string CreateCustomer(UserPaymentInfoDTO customerInfo);

        /// <summary>
        /// Updates a user's name and address information on paymentSpring
        /// </summary>
        /// <param name="paymentAddressInfo">The new information to be stored with the customer</param>
        void UpdateCustomerBillingInformation(PaymentAddressDTO paymentAddressInfo);

        /// <summary>
        /// Updates a user's card information on paymentSpring
        /// </summary>
        /// <param name="paymentCardInfo">The new information to be stored with the customer</param>
        void UpdateCustomerCardInformation(PaymentCardDTO paymentCardInfo);

        /// <summary>
        /// Deletes a users information from paymentSpring
        /// </summary>
        /// <param name="customerID">The id of the customer to delete</param>
        void DeleteCustomer(string customerID);
    }
}
