using Core.DTOs;
using System;
using System.Collections.Generic;
using System.Text;

namespace Core.Interfaces
{
    /// <summary>
    /// Sets payment info in Payment Spring
    /// </summary>
    interface ISetPaymentInfoAccessor
    {
        /// <summary>
        /// Creates a new customer with paymentSpring
        /// </summary>
        /// <param name="customerInfo">The information neccessary</param>
        /// <returns>The customer id generated by paymentSpring</returns>
        string CreateCustomer(CreateCustomerDTO customerInfo);
        
        /// <summary>
        /// Creates a token for the users credit card
        /// </summary>
        /// <param name="tokenInfo">All information required to create a token with paymentSpring</param>
        /// <returns>Returns the token that is generated by paymentSpring</returns>
        string CreateToken(CreateTokenDTO tokenInfo);

        /// <summary>
        /// Updates a users information on paymentSpring
        /// </summary>
        /// <param name="customerInfo">The new information to be stored with the customer</param>
        void UpdateCustomer(CreateCustomerDTO customerInfo);
    }
}
