using Core.DTOs;
using System;
using System.Collections.Generic;
using System.Text;

namespace Core.Interfaces
{
    /// <summary>
    /// Sets payment info in Payment Spring
    /// </summary>
    interface ISetPaymentInfoAccessor
    {
        /// <summary>
        /// Creates a new customer with paymentSpring
        /// </summary>
        /// <param name="customerInfo">The information neccessary</param>
        /// <returns>The customer id generated by paymentSpring</returns>
        string CreateCustomer(UserPaymentInfoDTO customerInfo);

        /// <summary>
        /// Updates a users information on paymentSpring
        /// </summary>
        /// <param name="customerInfo">The new information to be stored with the customer</param>
        void UpdateCustomer(UserPaymentInfoDTO customerInfo);
    }
}
